name: Hello World Workflow

# Trigger the workflow on push events to the main branch
on:
  push:
    branches: [ "main" ]

jbs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World!"
